---
Standards:

  -
    Title: Kickoff Meeting
    Description: Welcome to the Teach In!
    UID: 90057dfa-4a22-4c01-9fed-d74b602438bb
    SuccessCriteria:
      - success criteria
    ContentFiles:
      - 
       Type: Lesson
       UID: e0a1f3cb-8fb1-414c-b863-8e3a90efb3ef 
       Path: /kickoff/overview.md
  -
    Title: Racism & Intersectionality 
    Description: Our topic for May
    UID: c8cd308a-a2d2-46c0-b06d-a291a9f26506
    SuccessCriteria:
      - success criteria
    ContentFiles:
      - 
       Type: Lesson
       UID: 85056e70-461e-43e9-be3f-8b09e1ba43e6 
       Path: /racism-intersectionality/overview.md

  -
    Title: Gender Identity & Expression 
    Description: Our topic for June
    UID: 493fd073-3e56-43de-b4d6-fdf59992dbf3 
    SuccessCriteria:
      - success criteria
    ContentFiles:
      - 
       Type: Lesson
       UID: cbe8058f-e730-45ad-abc8-c6f041ccb179  
       Path: /gender/overview.md

  -
    Title: Resource Library
    Description: One stop shop for resources
    UID: d31b1693-031e-4f8c-a691-9d47ae53db14
    SuccessCriteria:
      - success criteria
    ContentFiles:
      - 
       Type: Lesson
       UID: b95c0b8f-6d1d-4795-a8a0-bdcfa37a7e85
       Path: /resource-library/resources.md
