
Standards:
- Title: Welcome to the Teach In!
  UID: 8eeb97cb-e384-49d2-b916-eadc63830dc2 
  Description: Our first Teach In lesson!
  SuccessCriteria:
  - success criteria
  ContentFiles:
  - Type: Lesson
    Path: /may/overview.md
    UID: 5bbfc74b-8532-496f-8189-c839b5408931 
